//@@ LIST ALL MOVIES
export const FETCH_MOVIES = '@@MOVIES/FETCH_MOVIES'
export const FETCH_MOVIES_SUCCESS = '@@MOVIES/FETCH_MOVIES_SUCCESS'
export const FETCH_MOVIES_ERROR = '@@MOVIES/FETCH_MOVIES_ERROR'
export const START_LOADING_MOVIE = '@@MOVIES/START_LOADING_MOVIE'
export const FINISH_LOADING_MOVIE = '@@MOVIES/FINISH_LOADING_MOVIE'

//@@ SEARCH MOVIE
export const CHANGE_SEARCH_TERM = '@@PRODUCT/CHANGE_SEARCH_TERM'

//@@ DETAIL MOVIE
export const GET_MOVIE_DETAIL = '@@MOVIES/GET_MOVIE_DETAIL'
export const GET_MOVIE_DETAIL_SUCCESS = '@@MOVIES/GET_MOVIE_DETAIL_SUCCESS'
export const GET_MOVIE_DETAIL_ERROR = '@@MOVIES/GET_MOVIE_DETAIL_ERROR'
export const START_LOADING_MOVIE_DETAIL = '@@MOVIES/START_LOADING_MOVIE_DETAIL'
export const FINISH_LOADING_MOVIE_DETAIL = '@@MOVIES/FINISH_LOADING_MOVIE_DETAIL'

//@@ MOVIE REVIEW
export const GET_MOVIE_REVIEWS = '@@MOVIES/GET_MOVIE_REVIEWS'
export const GET_MOVIE_REVIEWS_SUCCESS = '@@MOVIES/GET_MOVIE_REVIEWS_SUCCESS'
export const GET_MOVIE_REVIEWS_ERROR = '@@MOVIES/GET_MOVIE_REVIEWS_ERROR'
export const START_LOADING_MOVIE_REVIEWS = '@@MOVIES/START_LOADING_MOVIE_REVIEWS'
export const FINISH_LOADING_MOVIE_REVIEWS = '@@MOVIES/FINISH_LOADING_MOVIE_REVIEWS'